Use the new yolks repo for Pterodactyl images
PaperMC/PaperDocs pull request #103
Opened 2021-08-17 20:21 UTC by fabianmakila

Pterodactyl now provides Java 8, 11 and 16 images by default. The Java images in the `ghcr.io/pterodactyl/yolks` repository are preferred over the ones in `quay.io/parkervcp/pterodactyl-images`.

I've also changed the instructions to better match the current panel behavior. English is not my first language, so I'd be more than happy to get some feedback from a native speaker.

2021-08-17 20:29 UTC, sulu5890 requested changes
Looks fine, however the image will come up very large. Please either upload a smaller image, or set a display size. Here's [how you do that](https://github.com/PaperMC/PaperDocs/blame/master/source/java-update/index.rst#L66).

2021-08-17 20:41 UTC, fabianmakila commented
> Looks fine, however the image will come up very large. Please either upload a smaller image, or set a display size. Here's [how you do that](https://github.com/PaperMC/PaperDocs/blame/master/source/java-update/index.rst#L66).

I've now added a width for the image. I can also decrease the original image resolution if the current resolution is too large.

2021-08-17 20:44 UTC, NoahvdAa commented on source/java-update/index.rst
> +If you are running older panel version, manually enter the image url in the custom image field.
```suggestion
If you are running an older panel version, manually enter the image url in the custom image field.
```

2021-08-17 20:50 UTC, NoahvdAa approved these changes

2021-08-18 06:21 UTC, Proximyst requested changes

2021-08-18 06:21 UTC, Proximyst commented on source/java-update/index.rst
> +Proceed by selecting ``ghcr.io/pterodactyl/yolks:java_16`` from the *Image* dropdown under *Docker Container Configuration*.
Dropdowns? The image must be updated for this.

2021-08-18 15:06 UTC, fabianmakila commented on source/java-update/index.rst
> +Proceed by selecting ``ghcr.io/pterodactyl/yolks:java_16`` from the *Image* dropdown under *Docker Container Configuration*.
You can see the first commit includes a newer image of the panel which has the dropdown included. Rich diff in GH for some reason doesn't show the updated image.

2021-08-21 02:01 UTC, sulu5890 approved these changes

2021-08-21 02:04 UTC, merged