Added ServerFlex to Java Version page
PaperMC/PaperDocs pull request #112
Opened 2021-09-09 22:58 UTC by alandoherty

Added ServerFlex to Java 16 version page as we still have some confused customers trying to update manually and this is the first result on Google. Let me know if I need to make any changes.

2021-09-09 23:10 UTC, sulu5890 requested changes
Thank you for adding this, just a small change to better fit the style of this page.

2021-09-09 23:10 UTC, sulu5890 commented on source/java-update/index.rst
> +<https://serverflex.io/help/article/change-java-version-on-minecraft-server>`_
```suggestion
ServerFlex defaults to Java 8, but will automatically select Java 16
where appropriate. To manually configure the java version, navigate
to the settings page, and select ``Java Version``. More information can be found
`in ServerFlex's support article. <https://serverflex.io/help/article/change-java-version-on-minecraft-server>`_
```

2021-09-09 23:20 UTC, Proximyst requested changes

2021-09-09 23:20 UTC, Proximyst commented on source/java-update/index.rst
> +.. image:: java-update-assets/serverflex-java-version.png
All images have to be prefixed a new line with `|br|`:
```suggestion
.. image:: java-update-assets/serverflex-java-version.png

|br|
```

2021-09-10 11:28 UTC, alandoherty commented
Applied changes, looks cleaner now thanks!

2021-09-10 12:31 UTC, Oharass approved these changes

2021-09-10 13:00 UTC, Proximyst approved these changes

2021-09-10 13:02 UTC, merged