Adding a page for Aikar's tunings to PaperDocs
PaperMC/PaperDocs pull request #129
Opened 2021-11-28 03:02 UTC by mja00

I noticed Aikar's blog has been getting quite sluggish lately, which I believe stops a good amount of people from learning what the flags are actually *doing* on their server. I did create a mirror of Aikar's blog post; however, after thinking a bit, I realized it's probably better to be in the docs itself as that'll be more official-looking than some random website that mirrors the content of the page. 

This PR keeps all the same content found on Aikar's blog post, just formatted slightly differently due to how RTD renders. I tried to keep each line in the file under a certain amount of characters, so you aren't horizontally scrolling through the blocks of text when updating/editing anything.

2021-11-29 02:16 UTC, sulu5890 commented
Thanks for the PR, it's is a great idea to have this content here. I don't really implementation however of copying the blogpost verbatim. This leads to sections that don't make sense for Paper's docs such as the "Recommended Server Software" section. If this is included here, it also shouldn't be a mirror of the blogpost by linking to it, rather an independent copy of the same material.

Really what I would want is just to have the flags to copy/paste, as well as the breakdown of what each one does but reword it to not sound like a blogpost by removing stuff like "my server" etc. If you've got time to do this that'd be great, else I'm more than happy to do it. Thanks regardless

2021-11-29 02:23 UTC, mja00 commented
Yeah, I can cut out all the blog post-related stuff and make it more just the needed info. I wasn't sure what was wanted so I just went with verbatim to start. I'll probably get that done sometime tomorrow.

2021-11-29 23:23 UTC, sulu5890 requested changes
Overall this looks good; just a couple of comments. Also needs a look from Aikar before merging.

2021-11-29 23:23 UTC, sulu5890 commented on source/server/aikar-tuning.rst
> +The JVM Startup Flags to use – MC 1.15+ (Java 8+, MC 1.8+) Update
```suggestion
Recommended JVM Startup Flags
```

This section header seems a bit off for a docs article, something like that would be better.

2021-11-29 23:23 UTC, sulu5890 commented on source/server/aikar-tuning.rst
> +**Use these flags exactly, only changing Xmx and Xms. These flags work and scale accordingly to any size of memory, even 500MB but 1.15+ will not do well with such low memory…)**
```suggestion
**Use these flags exactly, only changing Xmx and Xms. These flags work and scale accordingly to any size of memory, even 500MB but modern Minecraft versions will not do well with such low memory…)**
```

I'd like to avoid Minecraft version-specific stuff as much as possible, as it just leads to people asking "Will this work for 1.19 etc."

2021-11-29 23:23 UTC, sulu5890 commented on source/server/aikar-tuning.rst
> +These flags are recommended for ALL versions of Minecraft! 1.8 all the way to 1.15+, use this set.
```suggestion
```
See above, will lead to more questions.

2021-11-29 23:23 UTC, sulu5890 commented on source/server/aikar-tuning.rst
> +
Something here like "more memory ≠ more performance above a certain point", with the intent of preventing people from going out and buying 24gb from some shared host where that'll give them almost no benefit and just have them paying more.

2021-11-29 23:23 UTC, sulu5890 commented on source/server/aikar-tuning.rst
> +Aikar's Tuning
```suggestion
Aikar's Flags
```

Same for the file name, this is the much more common name and will be more recognizable.

2021-11-29 23:23 UTC, sulu5890 commented on source/server/aikar-tuning.rst
> +   **YOU HAVE UNUSED MEMORY! Unused memory is wasted memory.** G1 (and probably even CMS to a certain threshold, but we're only stating what we're sure about)
CMS has been removed, not super relevant to mention here anymore (as well as other references)

2021-11-29 23:23 UTC, sulu5890 commented on source/server/aikar-tuning.rst
> +======================
Inconsistent spacing throughout the document; keep one newline here and other places.

2021-12-01 00:03 UTC, mja00 commented
I'll probably do all of these tomorrow or Thursday, update launch days are always busy for me :P

2021-12-03 15:33 UTC, mja00 commented
First batch of suggestions done while I had some free time between classes, will get the others done soon™

2021-12-05 20:50 UTC, sulu5890 approved these changes

2021-12-05 20:50 UTC, sulu5890 commented on source/server/aikar-tuning.rst
> +=================================================================
```suggestion
Recommended JVM Startup Flags
=============================
```

2021-12-05 20:51 UTC, sulu5890 commented
Need Aikar's OK on this, but, otherwise looks good

2021-12-30 01:50 UTC, sulu5890 commented
Got Aikar's OK via discord. Thanks.

2021-12-30 01:51 UTC, merged