Update java version in FAQ
PaperMC/PaperDocs pull request #147
Opened 2022-01-09 14:17 UTC by NoahvdAa

2022-01-09 14:28 UTC, NotMyFault requested changes

2022-01-09 14:28 UTC, NotMyFault commented on source/about/faq.rst
> +don't already have a Java 17 Runtime, :doc:`it's easy to download and install</java-update/index>`.
The paragraph could be rephrased to outline that Paper requires the same Java version like Mojang does and then link to the Java guide, which takes care of it.
Otherwise we're swapping out numbers every few months.

2022-02-07 09:49 UTC, NoahvdAa commented on source/about/faq.rst
> +don't already have a Java 17 Runtime, :doc:`it's easy to download and install</java-update/index>`.
Thanks, changed

2022-02-07 10:07 UTC, MiniDigger commented
idk about this, do we really have the same requirements as mojang? in the past, ours were always higher, its just coincidence that they allign right now, its not a promise that this will always be the case (altho heres hoping they don't delay updates for crazy long periods now that their internal JDK team has an interest in releasing JDKs to their minecraft users)

2022-03-08 22:01 UTC, sulu5890 commented
partially done in https://github.com/papermc/docs by removing this and merging it into the getting-started section.

2022-03-08 22:01 UTC, closed without merging