Add Waterfall Docs
PaperMC/PaperDocs pull request #36
Opened 2020-06-24 11:12 UTC by finlaysawyer

I'd expect you'll have a few changes to make, but hopefully this should suffice for initial Waterfall documentation. I figured it would be easier to navigate and more structured to rename /server to /paper-server and then adding /waterfall-server. Of course, I can change this if not desirable. I've updated all of the references for it.

Closes #32

2020-07-17 07:26 UTC, electronicboy commented on source/index.rst
> +Running A Waterfall Server
Waterfall is a proxy, not a server

2020-07-17 07:28 UTC, electronicboy commented on source/waterfall-server/getting-started.rst
> +For more advanced Java tuning, see `Aikar's tuning page <https://mcflags.emc.gs>`_.
These flags aren't recommended for the proxy

2020-08-24 12:53 UTC, finlaysawyer commented
Thanks for the review, I've gone ahead and Implemented each of these - I added Aikar's flags separately underneath as this is essentially what's done with Paper as well.

2020-08-24 18:37 UTC, Proximyst requested changes

2020-08-24 18:37 UTC, Proximyst commented on source/waterfall/configuration.rst
> +* **description**: Sets whether to disable entity metadata rewriting.
Perhaps we should explain what it does?

2020-08-24 18:37 UTC, Proximyst commented on source/waterfall/getting-started.rst
> +Waterfall and Travertine require **Java 8** or newer to run. It should run fine
```suggestion
Waterfall and Travertine require **Java 8** or newer to run. It does run fine
```

2020-08-24 18:37 UTC, Proximyst commented on source/waterfall/getting-started.rst
> +Generally, LTS versions of Java are best supported, though you may have luck on newer versions.
```suggestion
Generally, LTS versions of Java are targeted, though you may have luck on newer versions.
```

2020-08-24 18:37 UTC, Proximyst commented on source/waterfall/getting-started.rst
> +``java -Xms512M -Xmx512M -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions``
I'd say we should rather link to Aikar's article in case they change. It also has info on Pterodactyl/Docker's memory limits and whatnot.

2020-08-24 18:37 UTC, Proximyst commented on source/waterfall/getting-started.rst
> +The amount of RAM can be set by changing the numbers in the ``-Xms`` and ``-Xmx``
```suggestion
The amount of memory can be set by changing the numbers in the ``-Xms`` and ``-Xmx``
```

This is strictly speaking the heap memory for the JVM.

2020-08-24 18:37 UTC, Proximyst commented on source/waterfall/getting-started.rst
> +arguments.
```suggestion
flags.
```

2020-08-24 18:37 UTC, Proximyst commented on source/waterfall/getting-started.rst
> +To configure your server, see the :doc:`../waterfall/configuration` page.
```suggestion
To configure your proxy, see the :doc:`../waterfall/configuration` page.
```

2020-08-24 18:37 UTC, Proximyst commented on source/waterfall/getting-started.rst
> +Running The Server
```suggestion
Running The Proxy
```

2020-08-24 18:37 UTC, Proximyst commented on source/waterfall/getting-started.rst
> +Getting A Server Jar
```suggestion
Getting A Proxy Jar
```

2020-08-24 18:37 UTC, Proximyst commented on source/waterfall/getting-started.rst
> +Paper provides runnable server jars directly from our `website's downloads page <https://papermc.io/downloads#Waterfall>`_.
```suggestion
Paper provides runnable proxy jars directly from our `website's downloads page <https://papermc.io/downloads#Waterfall>`_.
```

2020-08-24 18:37 UTC, Proximyst commented on source/waterfall/getting-started.rst
> +
Section on what Waterfall and Travertine *are*. Note that Travertine is Waterfall but 1.7 support.

2020-08-24 18:37 UTC, Proximyst commented on source/waterfall/getting-started.rst
> +To run the server, simply start it up like any other Java application.
```suggestion
To run the proxy, simply start it up like any other Java application.
```

2020-08-24 18:37 UTC, Proximyst commented on source/waterfall/getting-started.rst
> +Updating The Server
```suggestion
Updating The Proxy
```

2020-08-24 18:37 UTC, Proximyst commented on source/waterfall/getting-started.rst
> +To update the server, first stop it safely by executing the ``end`` command
```suggestion
To update the proxy, first stop it safely by executing the ``end`` command
```

2020-08-24 18:37 UTC, Proximyst commented on source/waterfall/getting-started.rst
> +and then replace the old waterfall jar with a new one. That's it.
```suggestion
and then replace the old proxy jar with a new one. That's it.
```

This is an article for two different proxies.

2020-08-24 18:40 UTC, Chew commented on source/waterfall/getting-started.rst
> +``java -Xms512M -Xmx512M -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions``
The flags aren't on the article (that I see), he put it in a pin in #waterfall-help I believe.

2020-08-24 18:41 UTC, Chew commented on source/waterfall/getting-started.rst
> +
Specifically 1.7.10 support ^

2020-08-24 18:41 UTC, Proximyst commented on source/waterfall/getting-started.rst
> +``java -Xms512M -Xmx512M -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions``
Bully Aikar into adding it then :>

2020-08-24 18:44 UTC, finlaysawyer commented on source/waterfall/getting-started.rst
> +``java -Xms512M -Xmx512M -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions``
Yeah I did have the article linked originally but electronicboy said to remove them as they're just for Paper, we can either keep them until/if they're added or just remove them for the time being?

2020-08-24 18:49 UTC, Chew commented on source/waterfall/configuration.rst
> +* **description**: Sets whether to disable entity metadata rewriting.
What *does* it do?

2020-08-24 19:42 UTC, finlaysawyer commented
I've made the minor changes in regards to grammar etc and added a section at the top explaining what Waterfall and Travertine are. I have added back the link to Aikar's post, but still leaving the Waterfall flags above as they can only be found in Discord currently. I've also provided a better explanation about disabling entity metadata rewriting from what I could gather from issues & Discord, feel free to make any corrections. Cheers again

2020-09-21 05:00 UTC, merged