Update configuration.rst
PaperMC/PaperDocs pull request #42
Opened 2020-11-08 18:36 UTC by TASelwyn

Adds lava-obscures option to the wiki documentation.

2020-11-08 20:22 UTC, Chew commented
Update the "last updated" at the top as well

2020-11-08 20:24 UTC, TASelwyn commented
> Update the "last updated" at the top as well

Ha, I didn't even know that existed 😆

2020-11-08 20:26 UTC, TASelwyn commented
Commited to the pull request branch to fix the date @Chew

2020-11-08 20:28 UTC, Proximyst requested changes

2020-11-08 20:28 UTC, Proximyst commented on source/server/configuration.rst
> +    - **description**: Whether or not to obfuscate blocks touching lava. (Note: Does not work well with non-stone-like ore textures)
What does "not work well" mean here? Make it clearer or drop that part.

2020-11-08 21:16 UTC, TASelwyn reviewed
fixed in a commit

2020-11-11 02:44 UTC, TASelwyn commented
@Proximyst Do you mind reviewing the change?

2020-11-11 05:43 UTC, Chew approved these changes
Looks good

2020-11-11 06:09 UTC, Proximyst approved these changes

2020-11-11 06:10 UTC, merged