Update getting-started.rst
PaperMC/PaperDocs pull request #43
Opened 2020-12-04 13:45 UTC by Heartz66

Requirements updated regarding recent update: https://papermc.io/forums/t/java-11-mc-1-17-and-paper/5615

2020-12-04 13:51 UTC, HexedHero commented
But it doesn't require 11, at least not yet. If anything it should say something like "requires Java 8 (Soon Java 11) or newer"

2020-12-04 14:01 UTC, Proximyst requested changes
Perhaps also something about the last 2 LTSes?

2020-12-04 14:01 UTC, Proximyst commented on source/server/getting-started.rst
> +Paper requires **Java 11** or newer to run. It should run fine on newer versions
```suggestion
Paper requires **Java 8** or newer to run, however this will be changed to **Java 11** as of 1.17. It should run fine on newer versions
```

2021-04-13 00:16 UTC, zachbr commented
This has been superceded by GH-49.

We appreciate your contribution. Just saw the other one first. Really this is our fault for taking this long to merge. Thanks anyway.

2021-04-13 00:16 UTC, closed without merging