Document undocumented config options.
PaperMC/PaperDocs pull request #60
Opened 2021-06-03 19:49 UTC by sulu5890

Adds documentation for:

* use-display-name-in-quit-message
* track-plugin-scoreboards
* map-item-frame-cursor-limit
* seed-based-feature-search
* only-players-collide
* allow-vehicle-collisions
* portal-search-vanilla-dimension-scaling
* fix-items-merging-through-walls
* disable-mob-spawner-spawn-egg-transformation
* fix-invulnerable-end-crystal-exploit
* max-growth-height.bamboo

which I believe to be the only currently undocumented config options in paper.yml. Also fixes a small warning during build.

I'm not so sure about my documentation of `use-display-name-in-quit-message` as it does not provide any more information than what you could get by reading the configuration name, however, I'm not sure of a better way to phrase it or what to add.

2021-06-03 19:59 UTC, Proximyst requested changes

2021-06-03 19:59 UTC, Proximyst commented on source/server/configuration.rst
> +* **description**: Whether the server should track plugin scoreboards with only dummy objectives. This is a breaking change, however provides a much more sensible default value.
80 character limit.

Perhaps note that this has a performance impact?

2021-06-03 20:46 UTC, Chew reviewed
And here I come with my grammar/wording changes... all optional and up for debate but great work nonetheless!

2021-06-03 20:46 UTC, Chew commented on source/server/configuration.rst
> +* **description**: Whether vehicles should also be able to collide while
Maybe document what vehicles are? I don't even know what they are to correct you 😂

2021-06-03 20:46 UTC, Chew commented on source/server/configuration.rst
> +* **description**: Whether item merges should be raytraced to prevent items
"from" should be after items.

2021-06-03 20:46 UTC, Chew commented on source/server/configuration.rst
> +   - **note**: This expects the full world to be generated with the same seed and generator.
"This assumes the seed and the generator have remained unchanged." maybe?

2021-06-03 20:46 UTC, Chew commented on source/server/configuration.rst
> +  dummy objectives. This is a breaking change, however provides a much more
```suggestion
  dummy objectives. This is a breaking change; however, it provides a much more
```

2021-06-03 20:47 UTC, Chew commented
Also be sure to update the "Last updated" part in the header

2021-06-03 21:00 UTC, sulu5890 commented on source/server/configuration.rst
> +* **description**: Whether item merges should be raytraced to prevent items
This should probably be rephrased, but putting from there would mean that the item itself is being raytraced, which sounds wrong as it's the path between the two items merging that is checked.

2021-06-03 21:05 UTC, sulu5890 commented on source/server/configuration.rst
> +* **description**: Whether vehicles should also be able to collide while
I'm not sure if documenting it here specifically would be the best as it is already sort of used elsewhere, and likely will in the future. Plus this will change with Minecraft updates, however, I'm open to opinions on this. Vehicles are minecarts, boats, etc.

2021-06-03 21:12 UTC, sulu5890 commented on source/server/configuration.rst
> +   - **note**: This expects the full world to be generated with the same seed and generator.
How is this?

2021-06-05 17:56 UTC, Proximyst commented on source/server/configuration.rst
> +* **description**: Whether vehicles should also be able to collide while
I don't think we should document this. It's a pretty widely used word.

2021-06-05 18:12 UTC, Proximyst commented on source/server/configuration.rst
> +* **description**: Whether item merges should be raytraced to prevent items
"Whether merging drops should raytrace the dropped items to prevent them merging through walls."?

2021-06-05 18:12 UTC, Proximyst commented on source/server/configuration.rst
> +   - **note**: This expects the full world to be generated with the same seed and generator.
Looks great!

2021-06-05 18:19 UTC, sulu5890 commented on source/server/configuration.rst
> +* **description**: Whether item merges should be raytraced to prevent items
That still sounds a bit clunky to me. Perhaps not mentioning raytracing at all and rather just documenting what it actually does. If you want to know how it works (other than the config name) you can see the patch. Something like:

> Whether items should be prevented from merging through walls. Enabling this will incur a performance degradation. This is only necessary when ``merge-radius.item`` (spigot.yml) is large enough to merge items through walls.

2021-06-05 18:26 UTC, Proximyst commented on source/server/configuration.rst
> +* **description**: Whether item merges should be raytraced to prevent items
Sounds fine by me! Happy to merge once that's changed :)

2021-06-05 18:30 UTC, sulu5890 commented on source/server/configuration.rst
> +* **description**: Whether item merges should be raytraced to prevent items
done

2021-06-05 18:30 UTC, Proximyst approved these changes

2021-06-05 18:31 UTC, merged