Update documentation for version 2 of the API
PaperMC/PaperDocs pull request #70
Opened 2021-06-10 17:42 UTC by TwoLeggedCat

Even if these docs are not used, the v1 docs should be removed to prevent people from ignoring the deprecation notice and using it.
I probably missed a few things, and went over the 80 character line limit a few times, so I don't expect this to be merged as-is.

2021-06-10 17:52 UTC, Proximyst requested changes
Looks fine

2021-06-10 17:52 UTC, Proximyst commented on source/site/api.rst
> +that of `v1`, the below instructions are kept for completion.
```suggestion
While downloads using the ``v2`` API should have reasonable names compared to
that of ``v1``, the below instructions are kept for completion.
```

2021-06-10 17:52 UTC, Proximyst commented on source/site/api.rst
>  ------------
```suggestion
PROJECT
-------
```

2021-06-10 17:52 UTC, Proximyst commented on source/site/api.rst
>  ---------------
```suggestion
VERSION
-------
```

2021-06-10 17:52 UTC, Proximyst commented on source/site/api.rst
> +--------------
```suggestion
API Versions
------------
```

2021-06-10 22:08 UTC, Chew reviewed
Great work! Just some general comments

2021-06-10 22:08 UTC, Chew commented on source/site/api.rst
> +- ``travertine`` - The Travertine proxy; Waterfall, but supprting Minecraft 1.7. Now deprecated.
```suggestion
- ``travertine`` - The Travertine proxy; Waterfall, but supporting Minecraft 1.7. Now deprecated.
```

2021-06-10 22:08 UTC, Chew commented on source/site/api.rst
> +which is not recommended and, in rare cases, can lead to world corruption.
This warning seems a little scary. Can it just be reduced to "not recommended."?

2021-06-10 22:08 UTC, Chew commented on source/site/api.rst
> +Example getting a listing of available project versions for waterfall:
```suggestion
Example getting a listing of available project versions for Waterfall:
```

2021-06-10 22:08 UTC, Chew commented on source/site/api.rst
> +
```suggestion

```

2021-06-10 22:08 UTC, Chew commented on source/site/api.rst
> +    435,
```suggestion
    435
```

2021-06-10 22:08 UTC, Chew commented on source/site/api.rst
> -    content-length: 13713179
Why was this removed?

2021-06-10 22:09 UTC, TwoLeggedCat commented on source/site/api.rst
> -    content-length: 13713179
Accident. I copied the new headers in, thought that wasn't there originally, and took it out.

2021-06-10 22:09 UTC, TwoLeggedCat commented on source/site/api.rst
> +    435,
Yeah I cut a bunch of builds off to not make it huge and missed that

2021-06-10 22:11 UTC, TwoLeggedCat commented on source/site/api.rst
> +which is not recommended and, in rare cases, can lead to world corruption.
"discouraged"? sounds better imo

2021-06-14 04:24 UTC, sulu5890 reviewed
Overall it seems like you're trying to port the v1 documentation over to v2 and I'm not sure if that's the right way to go about it, specifically because [the swagger docs](https://papermc.io/api) have already replaced the bulk of it and some sections that are preserved no longer seem relevant.

I think a better approach to the documentation of the API here would be to link to the swagger docs for explaining the different routes/endpoints, and using this as a place for providing some basics of things like how to use curl and jq with the API as that's the type of thing that people seem to actually struggle with. It could also be used as supplementary material to the swagger docs answering questions such as "In the downloads schema will "application" always be the main program (paper, waterfall, etc)? If not, will the main program always be listed first? Can I assume the versions will always be in order or do I need to filter through them finding the largest number? Can I assume that for the paper project the filename will always be `paper-$version-$build.jar`?" etc. rather than attempting to replace the swagger does entirely.

This is just one opinion though, and in no way the definitive answer to documenting this. I'm hoping to more start a discussion of what form this documentation should actually take as I'm not sure how effective it is in it's current form.

2021-06-14 04:24 UTC, sulu5890 commented on source/site/api.rst
>   }
I understand what you're trying to do here, but I'm not sure if it's really necessary. This part is already documented via [swagger](https://papermc.io/api) and documenting essentially the same thing here does not make all that much sense and is just another place to maintain the same set of information.

2021-06-14 04:25 UTC, TwoLeggedCat commented on source/site/api.rst
> +that of ``v1``, the below instructions are kept for completion.
Yeah I kept it for that last part, but I can remove the rest.

2021-06-14 04:26 UTC, TwoLeggedCat commented on source/site/api.rst
> +which is not recommended and, in rare cases, can lead to world corruption.
I wrote that because I felt like, if I didn't, people would just keep asking if there's a permalink. That being said, those people also probably didn't read the API docs anyway

2021-06-14 04:31 UTC, sulu5890 commented on source/site/api.rst
> +which is not recommended and, in rare cases, can lead to world corruption.
I guess more of what I meant here is that I'm not sure if calling back to the v1 API is such a good idea as it will stop working in the near future. I think just mentioning it in any way that could drive people to use it beyond saying not to use it (especially as it is still very popular) should be avoided, especially as there are [people like this](https://canary.discord.com/channels/289587909051416579/289587909051416579/852569889838334032) who will continue to use it even though it is deprecated because it currently works and is easier.

2021-06-14 04:32 UTC, TwoLeggedCat commented
The purpose of this PR was simply because people are intimidated by the Swagger docs, even though they're very useful and even provide a tool to generate the request for you. If we don't want a documentation page on v2, IMHO, we simply don't want it at all. We're not the `curl` man page, and `curl` itself has very good, well-formatted documentation aside from the "ugly" man page. We could provide a very basic overview which tells how to set the name of the download (that's about all I can think of that would be needed anyway) and links to the `curl` and `wget` docs, but, at that point, it could simply be a footer on the "Getting Started" page with a link to the Swagger docs as well.
// @sulu5890

2021-06-14 04:38 UTC, TwoLeggedCat commented on source/site/api.rst
> +which is not recommended and, in rare cases, can lead to world corruption.
That part of the PR would be better after the complete removal of v1, as it would serve to say "Yeah, we know, this was a thing before and it isn't now. This is intentional," but you are correct that it may cause people to use v1 instead. New users, however, wouldn't be able to at all because the link to the latest build has been removed from the docs. As for now, at least, remove the section entirely?

2021-06-14 18:55 UTC, Chew commented
I do agree the swagger docs are kinda confusing but I don't believe this PR is useless.

The example responses should be scrapped. However, some basic questions and answers should remain. How do I get versions for a project? Describe and demonstrate it. Swagger fails at describing things in a simple manner so this can definitely help with it, but it shouldn't be neglected. Do indeed link to it with "if you want to play around with it, go to swagger and blah blah".

Regarding curl, some example commands can be helpful, but as you said they don't need to be described. Most people don't care and just want a working command. The people who do care won't need these docs to learn more.

Finally, we were discussing at minimum having this page be a mini-FAQ, especially regarding the latest version endpoint.

2021-06-16 20:21 UTC, sulu5890 commented on source/site/api.rst
> +which is not recommended and, in rare cases, can lead to world corruption.
I don't think removing it is the right call as it will be a question people will have that does not have a good answer elsewhere. This is probably fine as it is.

2021-06-23 00:31 UTC, TwoLeggedCat commented
Updated.

2021-06-23 00:56 UTC, sulu5890 reviewed
I really like the changes you've made to this. I just have some small comments all of which of course are up for discussion and not in any way hard set requirements.

I'd still like to have some examples going over how to use the api with curl/jq or other common tools, however if that's out of the scope of what you wanted this pr to be that is perfectly fine- what that would take the form of and if it's something others would want here at all can be talked about more after this pr has been merged. And as you said, we aren't the curl/wget/jq manpages.

2021-06-23 00:56 UTC, sulu5890 commented on source/site/api.rst
> +This is intentional, as it was previously used to make auto-updating servers
The phrasing "it was previously used to make auto-updating servers" sounds a bit off, perhaps "it was previously used to make auto-updaters" or "it was previously primarily used to auto-update servers" or something like that.

2021-06-23 00:56 UTC, sulu5890 commented on source/site/api.rst
> +v2 of the API they will always be integers.
Saying "as of" makes it sound like a new thing. It might just be better to ditch that entirely and just say "they will always be integer"

2021-06-23 00:56 UTC, sulu5890 commented on source/site/api.rst
> +previously documented endpoint to obtain information about a build.
I might add a note here that you can not assume that the download name will always be `${project}-${version}-${build}.jar` as this is something I've commonly seen people doing.

2021-06-23 00:56 UTC, sulu5890 commented on source/site/api.rst
> +    please go to `<https://papermc.io/api/docs/>`__
This is good to have linked but I'm not sure if here is the best place as these docs cover more than is there. Perhaps just link this under "endpoint documentation" as that's what the swagger docs really are. I'd like to hear your opinion though.

2021-06-23 01:03 UTC, TwoLeggedCat commented on source/site/api.rst
> +v2 of the API they will always be integers.
That was there before about v1; I think that was just to say "this might change, but this is how it is not"

2021-06-23 01:07 UTC, TwoLeggedCat commented on source/site/api.rst
> +    please go to `<https://papermc.io/api/docs/>`__
The new docs are really just an overview, however you're right that it seems weird to put it in the warning box with v1's deprecation as it's completely unrelated. I do still think the swagger docs should be referred to as the "full documentation," as I don't think these docs even cover every endpoint, however it definitely needs to be moved.

2021-06-23 01:10 UTC, TwoLeggedCat commented on source/site/api.rst
> +This is intentional, as it was previously used to make auto-updating servers
The existing wording sounds fine to me, however `it had been primarily used to auto-update servers` is more accurate anyway. I'll use that.

2021-06-23 02:30 UTC, sulu5890 approved these changes
Okay I've read it over one more time and have made some additional notes. Sorry for not making some of these before. Other than this looks good to me.

2021-06-23 02:30 UTC, sulu5890 commented on source/site/api.rst
> +    previous one will soon be removed.__
```suggestion
    previous one will soon be removed.
```

No longer needed now that the link is gone.

2021-06-23 02:30 UTC, sulu5890 commented on source/site/api.rst
>  versions of Paper for specific versions of Minecraft.
Downloads API is for more than just paper now, perhaps "our software" or something like that, not sure of the best wording.

2021-06-23 02:30 UTC, sulu5890 commented on source/site/api.rst
> +please go to `<https://papermc.io/api/docs/>`
```suggestion
please go to `<https://papermc.io/api/docs/>`_
```

The link won't work without this

2021-06-23 02:30 UTC, sulu5890 commented on source/site/api.rst
> +and you query the API properly to get the name of each build.
```suggestion
Note that filenames are not guaranteed to follow the same naming format,
and you must query the API properly to get the name of each build.
```

This is probably fine as it is and you can change this however you want, just sounded a bit off to me in reading.

2021-06-23 02:39 UTC, TwoLeggedCat commented on source/site/api.rst
> +and you query the API properly to get the name of each build.
yeah you're right

2021-06-23 02:41 UTC, TwoLeggedCat commented
Done

2021-06-23 02:44 UTC, sulu5890 approved these changes

2021-07-13 17:02 UTC, merged