Replace java 8 minimum requirement with 16
PaperMC/PaperDocs pull request #76
Opened 2021-06-21 18:27 UTC by lucyy-mc

2021-06-21 18:31 UTC, sulu5890 commented on source/about/faq.rst
> +don't already have a Java 16 Runtime, `it's easy to download and install <https://adoptopenjdk.net/?variant=openjdk16&jvmVariant=hotspot>`_.
Perhaps rather than linking to adopt link to the [upgrading to java 16](https://paper.readthedocs.io/en/latest/java-update/index.html) guide.

2021-06-24 13:38 UTC, stepech commented
Perhaps would be good to update other Java mentions too, to have it all in one PR:
https://github.com/PaperMC/PaperDocs/blob/master/source/server/getting-started.rst#requirements

I've never used Waterfall, so idk how is it with requirements there, but here is another mention from their requirements page: https://github.com/PaperMC/PaperDocs/blob/19698454213718ffd14a0783039a232d397fb5f4/source/waterfall/getting-started.rst#requirements

2021-06-24 14:26 UTC, lucyy-mc commented
> Perhaps would be good to update other Java mentions too, to have it all in one PR:
> https://github.com/PaperMC/PaperDocs/blob/master/source/server/getting-started.rst#requirements

602727a addressed this

2021-06-24 14:41 UTC, stepech commented
> Paper requires **Java 8** or newer to run. It should run fine on newer versions
as well, such as Java 11 and 16, but certain plugins may have issues. Generally, LTS
versions of Java are best supported, though you may have luck on newer versions. 
**Java 16** will be required for future releases starting with Minecraft 1.17.
  If you are deploying a new server, consider starting with Java 16. 
  More information about this transition is available....

That's nice for sure, the thing is, those "future releases" are releases that are being distributed now - hence it is outdated as it refers to something in the future, what we have now. Also, "Paper requires Java 8..." also no longer case. Paper 1.17 - **most up to date release** - requires Java 16 and Paper 1.16 will one day, sooner or later move to legacy and so this requirement will become outdated too. One way of correcting this would be raising minimum requirement to Java 16 and mentioning that legacy versions/versions before 1.17 require min Java 8. The commit you linked is to **prepare** us for update, but as the update is already here, it is time to update documentation too. No longer point in saying "one day will something.." when the day is today.

2021-06-24 15:46 UTC, sulu5890 requested changes
stepech is also correct- other locations should be updated as well to reflect that 1.17 has now been released. Waterfall still requires 8 for the moment, so no change needed there.

2021-06-24 15:46 UTC, sulu5890 commented on source/about/faq.rst
> +don't already have a Java 16 Runtime, `it's easy to download and install </en/latest/java-update/index.html>`_.
```suggestion
don't already have a Java 16 Runtime, :doc:`it's easy to download and install</java-update/index>`.
```

This won't correctly link as is.

2021-07-13 16:36 UTC, sulu5890 approved these changes

2021-07-13 16:36 UTC, merged

2021-07-15 19:39 UTC, lucyy-mc commented
Oops sorry, i completely forgot i opened this pr