Add EnviroMc to the shared hosts list.
PaperMC/PaperDocs pull request #98
Opened 2021-08-01 17:44 UTC by KoxSosen

I added [EnviroMc](https://enviromc.host/index.php) to the hosts list.

2021-08-01 17:51 UTC, KoxSosen commented
![image](https://user-images.githubusercontent.com/67807644/127780635-28bc3767-41e0-4aeb-a81f-a17c1fd754de.png)

2021-08-01 18:00 UTC, Proximyst requested changes
Host must be put in alphabetical order to ensure we remain impartial.

2021-08-01 18:22 UTC, KoxSosen commented
Done ^_^

2021-08-01 21:43 UTC, Proximyst approved these changes
Otherwise, looks fine to me

2021-08-01 21:43 UTC, Proximyst commented on source/java-update/index.rst
> +Startup -> Docker Image option, and select Java 16, as shown below.
Please italicise the website locations as done for other hosts.

2021-08-02 14:21 UTC, KoxSosen commented on source/java-update/index.rst
> +Startup -> Docker Image option, and select Java 16, as shown below.
Done, please let me know if this is good.

2021-08-02 16:01 UTC, merged